#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10
#define MULTITASK_OS_KERNELSHELL_TOTAL_INTERRUPTS 512

#define MULTITASK_OS_KERNELSHELL_HEAP_SIZE_BYTES 104857600 // 100MB, 1024*1024*100
#define MULTITASK_OS_KERNELSHELL_HEAP_BLOCK_SIZE 4096 // 4KB
#define MULTITASK_OS_KERNELSHELL_HEAP_ADDRESS 0x01000000 // 16MB
#define MULTITASK_OS_KERNELSHELL_HEAP_TABLE_ADDRESS 0x00007E00 // 2KB


#define MULTITASK_OS_KERNELSHELL_SECTOR_SIZE 512 // 512 bytes

#define MULTITASK_OS_KERNELSHELL_MAX_FILESYSTEMS 12
#define MULTITASK_OS_KERNELSHELL_FILE_DESCRIPTOR 512

#define MULTITASK_OS_KERNELSHELL_MAX_PATH 108
#define MULTITASK_OS_KERNELSHELL_TOTAL_GDT_SEGMENTS 6

#define MULTITASK_OS_KERNELSHELL_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define MULTITASK_OS_KERNELSHELL_USER_PROGRAM_STACK_SIZE 1024 * 16
#define MULTITASK_OS_KERNELSHELL_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000

// stack grows down by default in intel architecture
#define MULTITASK_OS_KERNELSHELL_PROGRAM_VIRTUAL_STACK_ADDRESS_END MULTITASK_OS_KERNELSHELL_PROGRAM_VIRTUAL_ADDRESS_START - MULTITASK_OS_KERNELSHELL_USER_PROGRAM_STACK_SIZE

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b
#endif
